chore: Update pre-commit configuration, tools and codebase (#743)
* pre-commit: Add pyupgrade

pyupgrade ensures the latest Python syntax supported is used.

* Run pre-commit

check yaml...............................................................Passed
fix end of files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing packages/solara-widget-manager8/tsconfig.json
Fixing packages/solara-widget-manager8/src
Fixing packages/solara-widget-manager8/style

trim trailing whitespace.................................................Passed
pyupgrade................................................................Failed
- hook id: pyupgrade
- exit code: 1
- files were modified by this hook

Rewriting solara/website/pages/doc_use_download.py

codespell................................................................Passed
ruff.....................................................................Passed
ruff-format..............................................................Passed
mypy.....................................................................Passed

* pre-commit: Update ruff version, use current repo

Use the latest ruff version (v0.6.1) from the current official ruff repo

* Use `is` for type comparisons

Fix ruff E721 Use `is` and `is not` for type comparisons, or `isinstance()` for isinstance checks

* Remove redefinition of unused `stack`

Fix ruff F811 in solara\toestand.py:148:40: F811 Redefinition of unused `stack` from line 147

* Run ruff on Jupyter Notebooks

Ruff now also works on Jupyter notebooks by default

* Revert "Run pre-commit"

This reverts commit f530ef8db75331922416bedc3be3e7766797d097.

* CI: Update code-quality to use Python 3.9 and 3.12

Python 3.9 is the lowest version pre-commit supports. See https://github.com/pre-commit/pre-commit/pull/3042

* Run pre-commit pyupgrade

* Fix pre-commit config warning in mypy hook

Fix: [WARNING] The 'exclude' field in hook 'mypy' is a regex, not a glob -- matching '/*' probably isn't what you want here

In regex, `.` matches any character except a newline, and `*` matches zero or more of the preceding element (in this case, any character). `.*` effectively replaces the `/*` glob pattern.

* Pre-commit: add check-toml, update mypy syntax